package bundle

import "text/template"

var goTpl = template.Must(template.New("gen").Parse(tpl))

const tpl = `// Code generated by bundle. DO NOT EDIT.

package {{ .PackageName }}


import (
	"github.com/golangee/bundle"
	"time"
)

// BundleVersion contains the hash of all embedded files and their bundle options.
const BundleVersion = "{{.Version}}"

// Bundle contains all embedded named resources.
var Bundle = bundle.Make(
		
		{{ range .Resources }}
			{{.FactoryMethod}},
		{{ end }}
)


{{ range .Blobs }}
const {{.ConstName}} = {{.Data}}
{{ end }}
`
